# Generated by Django 3.2.16 on 2023-01-03 19:02

import django.core.validators
from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='pdf_cours',
            field=models.FileField(blank=True, storage=djongo.storage.GridFSStorage(base_url='/static/myfiles/', collection='myfiles'), upload_to='static/upload/Cours', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
