# Generated by Django 3.2.16 on 2023-01-03 19:51

import django.core.validators
from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cours_pdf_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='pdf_cours',
            field=models.FileField(blank=True, storage=djongo.storage.GridFSStorage(base_url='/Cours/', collection='Cours'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
