# Generated by Django 4.1.5 on 2023-01-04 02:39

import django.core.validators
from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cours_pdf_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='pdf_cours',
            field=models.FileField(blank=True, storage=djongo.storage.GridFSStorage(base_url='/myfiles/', collection='myfiles'), upload_to='Cours', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='td',
            name='pdf_TD',
            field=models.FileField(storage=djongo.storage.GridFSStorage(base_url='/myfiles/', collection='myfiles'), upload_to='TD', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='td',
            name='pdf_TD_correction',
            field=models.FileField(blank=True, null=True, storage=djongo.storage.GridFSStorage(base_url='/myfiles/', collection='myfiles'), upload_to='TD', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='tp',
            name='pdf_TP',
            field=models.FileField(storage=djongo.storage.GridFSStorage(base_url='/myfiles/', collection='myfiles'), upload_to='TP', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
